#7305 Restrict mobile app synchronization
SORMAS-Foundation/SORMAS-Project pull request #10885
Opened 2022-11-09 15:49 UTC by andrei7bal

- added a max change date feature type property with default value to X=30
- in case the feature configuration for limited synchronization is enabled, than entities that are last updated before currentDate - X will not be synced with mobile app
- all entities that are not updated before currentDate - X will be deleted from mobile app DB

Fixes #7305

2022-11-10 08:55 UTC, MateStrysewske requested changes
Resolve the merge conflicts please

2022-11-14 08:51 UTC, MateStrysewske requested changes
Integrate the new `MAX_CHANGE_DATE_SYNCHRONIZATION` into the existing `LIMITED_SYNCHRONIZATION` feature type, don't invent a new one

2022-11-15 09:44 UTC, MateStrysewske requested changes
I think it would make sense to move the implementation of the new methods that you added to the services to the superclass and explicitely override them in classes where we don't want to use the limited synchronization, because otherwise, if we want to change something about the implementation, we need to change it in quite a lot of places.

Also, while reviewing this, I realised that there are quite some entities we don't need to apply this logic to because they're dependent on other entities being synchronised in the first place, so you can remove the logic from those:
- Clinical visits
- Event participants
- Additional tests
- Pathogen tests
- Prescriptions
- Treatments
- Visits

Also, there are test failures, please make sure they're not related to your changes.

2022-11-15 09:44 UTC, MateStrysewske commented on sormas-api/src/main/java/de/symeda/sormas/api/feature/FeatureTypeProperty.java
> +	MAX_CHANGE_DATE_SYNCHRONIZATION(Integer.class),
```suggestion
	MAX_CHANGE_DATE_PERIOD(Integer.class),
```

(Just saw that this is how it's defined in the issue)

2022-12-07 13:19 UTC, MateStrysewske requested changes
I get synchronization errors when events are removed from the device because apparently event participants belonging to that event are still synchronized; I guess this is because when deciding which event participants we synchronize, we use the event user filter, but we didn't take into account the new restrictions there.

This problem can theoretically occur for other entities as well.

This means that each user filter of the entities that we've implemented limited synchronization based on change date now, the user filter needs to be extended accordingly (such as the case user filter was extended when we introduced the "EXCLUDE_NO_CASE_CLASSIFIED_CASES" property.

2023-01-10 14:08 UTC, sergiupacurariu approved these changes

2023-01-10 14:11 UTC, merged