Feature 11517 cleanup merge error messages
SORMAS-Foundation/SORMAS-Project pull request #12075
Opened 2023-06-13 08:10 UTC by leventegal-she

Fixes #11517

2023-06-13 08:33 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12075

2023-06-14 14:19 UTC, carina29 requested changes

2023-06-14 14:19 UTC, carina29 commented on sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
> +			if (editPermission == EditPermissionType.OUTSIDE_JURISDICTION) {
I've found a corner case when we have multiple problems: Outside jurisdiction and not enough user rights.
At first I've tried the merge without all the necessary user rights ( the message was correct and in the logs we can see the missing user righst):
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/fd221c39-9af5-42c5-bd4b-99cf265747f8)

After that I've changed the EditPermission Type to be OUTSIDE_JURISDICTION:
![OutsideJurisdictionAndNotEditable](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/67006f05-ec41-47c6-a87a-e8955b7fc92a)

The message that the entity is outside the jurisdiction appears but the other problem ( missing user rights) will not be displayed as it is requested in one of the acceptance criterias:
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/96ac4d72-f762-4dc2-8ea3-9baa2da186a8)

2023-06-15 07:17 UTC, carina29 commented on sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseFacadeEjb.java
> +			if (editPermission == EditPermissionType.OUTSIDE_JURISDICTION) {
@leventegal-she we've discussed in the daily the missing acceptance criteria and @MateStrysewske agreed that is not that necessary to display multiple problems so there is no need for any changes.

2023-06-15 07:18 UTC, carina29 approved these changes

2023-06-20 10:50 UTC, merged