Feature 11796 create a new environment entity and index dto
SORMAS-Foundation/SORMAS-Project pull request #12076
Opened 2023-06-13 08:48 UTC by ChristopherRiedel

Fixes #11796

2023-06-15 08:02 UTC, MateStrysewske requested changes
@ChristopherRiedel Test failures :)

2023-06-16 12:56 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12076

2023-06-19 09:12 UTC, MateStrysewske requested changes
Please change the database types and length constraints of all fields that I've specified as using the datatype "text" in the issue description (i.e. use text instead of varchar, and CHARACTER_LIMIT_TEXT)

2023-06-19 09:12 UTC, MateStrysewske commented on sormas-app/app/src/main/java/de/symeda/sormas/app/backend/caze/Case.java
> +public class
I guess this is an unintended change

2023-06-19 09:12 UTC, MateStrysewske commented on sormas-backend/src/main/java/de/symeda/sormas/backend/environment/EnvironmentFacadeEjb.java
> +//			final EnvironmentQueryContext environmentQueryContext = new EnvironmentQueryContext(cb, cq, environment, environmentJoins);
Remove this if it's not needed anymore

2023-06-19 09:12 UTC, MateStrysewske commented on sormas-rest/src/main/java/de/symeda/sormas/rest/exception/mappers/CatchAllExceptionMapper.java
> +		exception.printStackTrace();
Remove this line (was probably intended for testing?)

2023-06-20 06:47 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12076

2023-06-20 06:57 UTC, MateStrysewske requested changes
Data type changes should also be applied to the Android app

2023-06-20 09:10 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12076

2023-06-21 10:52 UTC, MateStrysewske requested changes
Character limits need to be changed in the app entity class as well

2023-06-22 09:49 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12076

2023-06-22 11:31 UTC, MateStrysewske approved these changes

2023-06-22 11:31 UTC, merged