#11946: Allow users to link/unlink event groups to events they own
SORMAS-Foundation/SORMAS-Project pull request #12100
Opened 2023-06-20 11:37 UTC by ChristopherRiedel

Fixes #11946

2023-06-21 12:18 UTC, carina29 commented
I've tested the feature branch and on my side and the first problem related to the linking of the eventgroups when the owner has a different jurisdiction is still reproducible on this feature branch:
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/3f1942c6-b14b-4acd-9064-9eef1e40beef)

The logs:
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/121a5930-7714-4f57-84a0-a7a4d9ce4d2d)

The user I'm logged in has the following region and district:
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/b31361e7-dcf7-40b7-b3ea-7b3d327654f7)


The event created by this user has the following region and district:
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/72f845a4-2593-451e-b243-9eb052195acf)
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/7a3622b4-660f-4a30-a991-df54abf8a9a1)

The user has the following rights:
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/01d0328c-bf82-4a0a-a1b6-6833d9b2f760)


The second problem described by @adinaflorea9 I could not reproduce anymore but I've found a very similar scenario related to the unlinking:
1) I've added the eventgroup as it was described by Adina (with the same user described above)
2) I've logged in with another user (National user) and linked multiple events to that event group (from different jurisdictions)
3) Logged back with the initial user and opened the event to which the eventgroup earilier was added and tried to unlink it, a message is displayed that the unlink is not possible because of the jurisdiction:
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/cc988c4a-ccbc-43fd-9b1a-9f1b12fb895e)

2023-06-21 12:19 UTC, carina29 requested changes

2023-06-21 12:19 UTC, carina29 commented on sormas-api/src/main/java/de/symeda/sormas/api/event/EventFacade.java
> +	boolean inJurisdictionOrOwned(String uuid);
I've added the findings as a comment to the PR

2023-06-28 13:11 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12100

2023-07-03 11:25 UTC, carina29 approved these changes

2023-07-03 11:30 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12100

2023-07-03 11:45 UTC, merged