#12068 - Improve backend duplicate removal
SORMAS-Foundation/SORMAS-Project pull request #12205
Opened 2023-06-23 09:35 UTC by MateStrysewske

Fixes #12068

2023-06-23 09:58 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12205

2023-06-27 12:04 UTC, sergiupacurariu requested changes

2023-06-27 12:04 UTC, sergiupacurariu commented on sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java
> +			typedQuery.setMaxResults(limit * 2);
limit set conducts to results higher than wanted

2023-06-27 12:04 UTC, sergiupacurariu commented on sormas-backend/src/main/java/de/symeda/sormas/backend/contact/ContactService.java
> +			query.setMaxResults(limit * 2);
limit set conducts to results higher than wanted

2023-07-27 08:02 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12205

2023-07-28 09:45 UTC, sergiupacurariu approved these changes

2023-07-28 09:46 UTC, merged