#11365 - AccessDeniedException for National User when trying to creat…
SORMAS-Foundation/SORMAS-Project pull request #12268
Opened 2023-07-07 12:46 UTC by sergiupacurariu

…e a new case starting from a case that has clinical visits

Fixes #11365

2023-07-11 08:02 UTC, MateStrysewske requested changes

2023-07-11 08:02 UTC, MateStrysewske commented on sormas-backend/src/main/java/de/symeda/sormas/backend/clinicalcourse/ClinicalVisitFacadeEjb.java
> +	public ClinicalVisitDto saveMergedCasesClinicalVisit(ClinicalVisitDto clinicalVisit, String caseUuid, boolean handleChanges) {
```suggestion
	public ClinicalVisitDto saveClinicalVisitForMergedCase(ClinicalVisitDto clinicalVisit, String caseUuid, boolean handleChanges) {
```

Bit more self-explanatory to me

2023-07-13 13:56 UTC, sergiupacurariu commented on sormas-backend/src/main/java/de/symeda/sormas/backend/clinicalcourse/ClinicalVisitFacadeEjb.java
> +		if (!isCaseMerge) {
Indeed I think it can be removed altogether with the check method. Removed the if clause along with the method inside,

2023-07-13 14:17 UTC, sergiupacurariu commented on sormas-backend/src/main/java/de/symeda/sormas/backend/clinicalcourse/ClinicalVisitFacadeEjb.java
> +	public ClinicalVisitDto saveMergedCasesClinicalVisit(ClinicalVisitDto clinicalVisit, String caseUuid, boolean handleChanges) {
updated the method name

2023-07-17 07:35 UTC, MateStrysewske approved these changes

2023-07-17 07:35 UTC, merged