#12274 - reshared entities archiving/dearchiving will trigger a Survn…
SORMAS-Foundation/SORMAS-Project pull request #12303
Opened 2023-07-14 14:06 UTC by carina29

…et call

Fixes #12274

2023-07-14 14:28 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12303

2023-07-17 07:02 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12303

2023-07-17 07:50 UTC, MateStrysewske requested changes

2023-07-17 07:50 UTC, MateStrysewske commented on sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java
> +		List<Long> eventIds = getCaseIds(entityUuids);
```suggestion
		List<Long> caseIds = getCaseIds(entityUuids);
```

2023-07-17 07:50 UTC, MateStrysewske commented on sormas-backend/src/main/java/de/symeda/sormas/backend/caze/CaseService.java
> +		entityUuids.stream().forEach(uuid -> caseIds.add(this.getByUuid(uuid).getId()));
`stream()` call is unnecessary here (same in EventService)

2023-07-17 10:07 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12303

2023-07-17 12:16 UTC, MateStrysewske approved these changes

2023-07-17 12:16 UTC, merged