#12243 process documentation for automatic dependency update PRs
SORMAS-Foundation/SORMAS-Project pull request #12342
Opened 2023-07-24 14:40 UTC by MartinWahnschaffe

Fixes #12243

2023-07-24 15:03 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12342

2023-07-27 06:39 UTC, StefanKock requested changes
Some minor text changes

2023-07-27 06:39 UTC, StefanKock commented on docs/CONTRIBUTING.md
> +2. If all CI checks are successful, minor versions can be merged
"... minor and micro version updates can be merged."

2023-07-27 06:39 UTC, StefanKock commented on docs/CONTRIBUTING.md
> +3. For mayor version updates read the changelog to understand implications and possible migration steps of the update. \
"major" (typo)

2023-07-27 07:41 UTC, merged

2023-07-27 08:00 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12342