#12025 - Add an environment list for the mobile app
SORMAS-Foundation/SORMAS-Project pull request #12344
Opened 2023-07-24 17:47 UTC by sergiupacurariu

Fixes #12025

2023-07-24 18:13 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12344

2023-07-25 12:39 UTC, leventegal-she requested changes
I get `java.sql.SQLException: Unknown field 'wateruse' from the Android sqlite cursor, not in:[id, uuid, changeDate, creationDate, lastOpenedDate, localChangeDate, modified, snapshot, reportDate, reportingUser_id, environmentName, description, externalId, responsibleUser_id, investigationStatus, environmentMedia, waterType, otherWaterType, infrastructureDetails, otherInfrastructureDetails, waterUse, otherWaterUse, location_id]` when I try to open the environment list in the app

2023-07-26 06:56 UTC, sergiupacurariu commented on sormas-app/app/src/main/java/de/symeda/sormas/app/rest/SynchronizeDataAsync.java
> +				|| DateHelper.getFullDaysBetween(ConfigProvider.getLastObsoleteUuidsSyncDate(), new Date()) >= 0;
changed back to 1

2023-07-26 07:12 UTC, sergiupacurariu commented on sormas-app/app/src/main/java/de/symeda/sormas/app/util/DateFormatHelper.java
> +	public static String getLatLonLocation(Location location){
method moved to ViewHelper class

2023-07-26 08:11 UTC, sergiupacurariu commented on sormas-app/app/src/main/java/de/symeda/sormas/app/backend/common/DatabaseHelper.java
> +					"CREATE TABLE environments(id integer primary key autoincrement, uuid VARCHAR(36) NOT NULL UNIQUE, "
added new migration for the added changes

2023-07-26 08:56 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12344

2023-07-26 10:11 UTC, leventegal-she approved these changes

2023-07-26 10:23 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12344

2023-07-26 10:32 UTC, merged