#12390 - Added missing external message fields
SORMAS-Foundation/SORMAS-Project pull request #12404
Opened 2023-08-08 15:32 UTC by MateStrysewske

Fixes #12390

2023-08-08 16:54 UTC, leventegal-she commented
Please fix the failing test(s)

2023-08-09 09:58 UTC, MateStrysewske commented
@leventegal-she Fixed, please check again :)

2023-08-09 10:13 UTC, leventegal-she requested changes

2023-08-09 10:13 UTC, leventegal-she commented on sormas-backend/src/test/java/de/symeda/sormas/backend/externalmessage/ExternalMessageFacadeEjbMappingTest.java
> +		when(countryService.getByReferenceDto(source.getPersonCountry())).thenReturn(null);
would be more useful to mock also the country than assert that the right country has been mapped to dto

2023-08-09 10:19 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12404

2023-08-10 08:15 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12404

2023-08-10 09:38 UTC, merged