Feature 11721 environment sample entity
SORMAS-Foundation/SORMAS-Project pull request #12430
Opened 2023-08-18 11:11 UTC by leventegal-she

Fixes #11721

2023-08-18 14:21 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12430

2023-08-21 08:58 UTC, MateStrysewske requested changes
Please use FieldConstraints.CHARACTER_LIMIT_TEXT for all Strings except IDs in the DTO as well as mobile and web entities.

Very thorough work and great extensive tests :)

2023-08-21 08:58 UTC, MateStrysewske commented on sormas-api/src/main/resources/strings.properties
> +errorEnvironmentSampleNotEditable = This environment sample is not editable any more
```suggestion
errorEnvironmentSampleNotEditable = This environment sample is not editable anymore
```

2023-08-21 08:58 UTC, MateStrysewske commented on sormas-api/src/main/resources/strings.properties
> +errorEnvironmentSampleNoDispatchRight = You do not have the necessary user to change the dispatch status of this environment sample
```suggestion
errorEnvironmentSampleNoDispatchRight = You do not have the necessary user right to change the dispatch status of this environment sample
```

2023-08-21 08:58 UTC, MateStrysewske commented on sormas-api/src/main/resources/strings.properties
> +errorEnvironmentSampleNoReceivalRight = You do not have the necessary user to change the receival status of this environment sample
```suggestion
errorEnvironmentSampleNoReceivalRight = You do not have the necessary user right to change the receival status of this environment sample
```

2023-08-21 08:58 UTC, MateStrysewske commented on sormas-api/src/main/resources/strings.properties
> +messageEnvironmentSampleOutsideJurisdictionDeletionDenied = The sample outside user's jurisdiction cannot be deleted
```suggestion
messageEnvironmentSampleOutsideJurisdictionDeletionDenied = The environment sample outside user's jurisdiction cannot be deleted
```

2023-08-21 08:58 UTC, MateStrysewske commented on sormas-app/app/src/main/java/de/symeda/sormas/app/backend/common/DatabaseHelper.java
> +                        "CREATE TABLE environmentsamples(id integer primary key autoincrement, uuid VARCHAR(36) NOT NULL, changeDate TIMESTAMP NOT NULL, "
I believe the table is supposed to be written in camel case as well, i.e. `enviornmentSamples` - otherwise we could run into issues

2023-08-21 08:58 UTC, MateStrysewske commented on sormas-app/app/src/main/java/de/symeda/sormas/app/backend/environment/EnvironmentDtoHelper.java
> +        ;
```suggestion
        
```

2023-08-21 08:58 UTC, MateStrysewske commented on sormas-app/app/src/main/java/de/symeda/sormas/app/backend/environment/environmentsample/EnvironmentSample.java
> +    public static final String TABLE_NAME = "environmentsamples";
```suggestion
    public static final String TABLE_NAME = "environmentSamples";
```

2023-08-21 08:58 UTC, MateStrysewske commented on sormas-backend/src/main/resources/sql/sormas_schema.sql
> +    received                    boolean,
Add default false here as well for consistency

2023-08-21 08:58 UTC, MateStrysewske commented on sormas-backend/src/test/java/de/symeda/sormas/backend/environment/environmentsample/EnvironmentSampleServiceTest.java
> +		// community officer from different district should have access to all samples
```suggestion
		// community officer from different district should have no access to all samples
```

2023-08-21 08:58 UTC, MateStrysewske commented on sormas-backend/src/test/java/de/symeda/sormas/backend/environment/environmentsample/EnvironmentSampleServiceTest.java
> +		// surveillance supervisor from different district should have access to all samples
```suggestion
		// surveillance supervisor from different district should have no access to all samples
```

2023-08-22 06:53 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12430

2023-08-22 13:13 UTC, MateStrysewske requested changes
Everything else seems fine, you can merge the PR after fixing the semicolon :)

2023-08-22 16:47 UTC, merged