#12391 Add new eSanté pathogen test fields to the user interface
SORMAS-Foundation/SORMAS-Project pull request #12447
Opened 2023-08-23 08:02 UTC by leventegal-she

Fixes #12391

2023-08-23 08:29 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12447

2023-08-24 09:09 UTC, MateStrysewske requested changes
Looks good; just realised that we probably have to decouple the visibility for the normal CQ value field for Luxembourg; i.e. if the server country code is Luxembourg, always display the CQ value field irrespective of the selected test type.

2023-08-24 10:21 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12447

2023-08-25 06:55 UTC, MateStrysewske approved these changes

2023-08-25 06:55 UTC, merged