Feature 11571 environment import
SORMAS-Foundation/SORMAS-Project pull request #12475
Opened 2023-08-30 12:24 UTC by leventegal-she

Fixes #11571

2023-08-30 12:49 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12475

2023-09-04 09:31 UTC, sergiupacurariu commented
currently, it is possible to import an environment having EnvironmentMedia set to anything but WATER and also add data to fields like WaterType, InfrastructureDetails, UseOfWater which should be filled only if the EnvironmentMedia is set to Water. This data cannot be seen in the UI due to the constraints but this data is stored in the database.  It should not be possible to import a situation like the one described above.

2023-09-08 10:59 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12475

2023-09-11 14:47 UTC, sergiupacurariu requested changes

2023-09-11 14:47 UTC, sergiupacurariu commented on sormas-api/src/main/resources/validations.properties
> +environmentWaterFieldsSetWithNotWaterMedia = The following fields can be set only if the media type is not water: %s
not should be removed "water"  instead of "not water"

2023-09-14 13:12 UTC, sergiupacurariu approved these changes

2023-09-14 13:37 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12475

2023-09-14 13:47 UTC, merged