#12366 - Add facility to external messages
SORMAS-Foundation/SORMAS-Project pull request #12482
Opened 2023-09-01 10:19 UTC by MateStrysewske

Fixes #12366

2023-09-01 10:44 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12482

2023-09-04 06:51 UTC, leventegal-she requested changes

2023-09-04 06:51 UTC, leventegal-she commented on sormas-backend/src/main/java/de/symeda/sormas/backend/externalmessage/ExternalMessage.java
> +	public Facility getPersonFacility() {
Should be `@ManyToOne`

2023-09-04 07:55 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12482

2023-09-07 08:21 UTC, leventegal-she approved these changes

2023-09-07 08:41 UTC, merged

2023-09-07 09:05 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12482