#11566 Add an environment sample grid to the web app
SORMAS-Foundation/SORMAS-Project pull request #12512
Opened 2023-09-07 08:19 UTC by leventegal-she

Fixes #11566

2023-09-07 08:52 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12512

2023-09-07 09:39 UTC, MateStrysewske requested changes

2023-09-08 07:24 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12512

2023-09-11 07:44 UTC, MateStrysewske approved these changes

2023-09-14 07:55 UTC, merged