Feature 10249 increase postgre sql to min 12 and default 14
SORMAS-Foundation/SORMAS-Project pull request #12521
Opened 2023-09-08 07:53 UTC by sergiupacurariu

Fixes #10249

2023-09-08 08:24 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12521

2023-09-08 08:28 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12521

2023-09-08 08:34 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12521

2023-09-08 08:53 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12521

2023-09-11 13:51 UTC, sergiupacurariu commented on sormas-base/setup/server-setup.sh
> +        echo "ERROR: Found Database server ${PostgreSQL_VERSION}  This version is too old."
updated in all places

2023-09-13 12:00 UTC, MateStrysewske approved these changes

2023-09-13 12:00 UTC, MateStrysewske requested changes
Test failures

2023-09-13 14:43 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12521

2023-09-14 05:48 UTC, sergiupacurariu commented
> Test failures

fixed

2023-09-14 07:15 UTC, MateStrysewske approved these changes

2023-09-14 07:15 UTC, merged