Feature 12235 environment sample create edit
SORMAS-Foundation/SORMAS-Project pull request #12533
Opened 2023-09-15 07:55 UTC by leventegal-she

Fixes #12235

2023-09-15 08:18 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12533

2023-09-15 10:42 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12533

2023-09-19 08:58 UTC, MateStrysewske requested changes
Not the biggest fan of reproducing methods in EnvironmentSampleFacade that we already have in one of our interfaces, but I guess everything else would require a major refactoring, and that would definitely be out of scope for this issue, so it's fine.

Apart from that:

- otherSampleMaterial needs to be required if "Other" is selected
- Celsius symbol in temperature caption is not displayed correctly
- Fields that require a number should have a proper validation text if the user enters non-numeric characters (currently the text is "Could not convert value to Float"); see fields in AdditionalTestDto for examples
- Please remove the "Other" requested pathogen test from the checkbox list since we cover this by the additional text field; see my mobile app PR, I've done it there as well - the code should not fail if no pathogen named "OTHER" exists in the database
- Add some margin below the "Sent/Dispatched" and "Received" checkboxes
- As a National User/Admin WITHOUT the user right to edit receival information, I can still edit the receival information of environment samples
- As a National User/Admin WITHOUT the user right to edit dispatch information, I can still edit the dispatch information of environment samples
- As an Environment Officer, trying to open an environment sample through the side component of an environment sends me to a "The view could not be found" page

2023-09-19 08:58 UTC, MateStrysewske commented on sormas-backend/src/main/java/de/symeda/sormas/backend/common/AbstractCoreFacadeEjb.java
> +	protected abstract DeletableEntityType getCoreEntityType();
```suggestion
	protected abstract DeletableEntityType getDeletableEntityType();
```

2023-09-19 08:58 UTC, MateStrysewske commented on sormas-ui/src/main/java/de/symeda/sormas/ui/environment/EnvironmentSampleListComponent.java
> +	private final EnvironmentSampleList eventList;
```suggestion
	private final EnvironmentSampleList environmentSampleList;
```

2023-09-19 08:58 UTC, MateStrysewske commented on sormas-ui/src/main/java/de/symeda/sormas/ui/environment/EnvironmentSampleListComponent.java
> +			Label dispatchRecieveLabel = new Label();
```suggestion
			Label dispatchReceiveLabel = new Label();
```

2023-09-19 08:58 UTC, MateStrysewske commented on sormas-ui/src/main/java/de/symeda/sormas/ui/samples/environmentsample/EnvironmentSampleController.java
> +	public EnvironmentSampleController() {
Isn't this redundant and can be removed?

2023-09-21 08:43 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12533

2023-09-21 09:27 UTC, MateStrysewske requested changes
As an environment surveillance officer, I can edit environment samples that are not in my jurisdiction and for which I'm not the reporting user.

Also, please replace the temperature field with a normal text input field that only accepts float numbers; right now, it's not possible to put in floating point numbers, which would very likely result in accuracy issues, and since the field is a normal text input field in the mobile app, this would also result in display issues when a floating point number would be entered into the mobile app. Having a dropdown with all possible values is not really feasible in this situation I feel like, because we have a higher range of possible values than for human temperatures (which would result in A LOT of numbers in the dropdown list).

2023-09-21 12:29 UTC, MateStrysewske requested changes
Temperature field has to accept floating point numbers

2023-09-21 13:03 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12533

2023-09-21 13:19 UTC, merged