#12414 - Generate enum values based on country locale in Developer view
SORMAS-Foundation/SORMAS-Project pull request #12536
Opened 2023-09-15 14:57 UTC by carina29

Fixes #12414

2023-09-15 15:23 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12536

2023-09-15 15:28 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12536

2023-09-19 09:02 UTC, MateStrysewske requested changes

2023-09-19 09:02 UTC, MateStrysewske commented on sormas-api/src/main/java/de/symeda/sormas/api/contact/QuarantineType.java
> +	public String toEnumCaption() {
Please revert this change, the method is required like this

2023-10-09 11:57 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12536

2023-10-09 13:52 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12536

2023-10-10 07:36 UTC, MateStrysewske approved these changes

2023-10-10 07:36 UTC, merged