#11570 Add a basic export to the environment and environment sample d…
SORMAS-Foundation/SORMAS-Project pull request #12540
Opened 2023-09-18 06:39 UTC by leventegal-she

…irectories

Fixes #11570

2023-09-18 07:04 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12540

2023-09-19 09:50 UTC, MateStrysewske requested changes

2023-09-19 09:50 UTC, MateStrysewske commented on sormas-ui/src/main/java/de/symeda/sormas/ui/utils/ExportEntityName.java
> +	ENVIRONMeNT_SAMPLES("entityEnvironmentSamples", "environment samples"),;
```suggestion
	ENVIRONMENT_SAMPLES("entityEnvironmentSamples", "environment samples");
```

2023-09-21 06:49 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12540

2023-09-21 08:48 UTC, MateStrysewske requested changes

2023-09-21 08:48 UTC, MateStrysewske commented on sormas-ui/src/main/java/de/symeda/sormas/ui/utils/ExportEntityName.java
> +	ENVIRONMENT_SAMPLES("entityEnvironmentSamples", "environment samples"),;
Remove the comma here as well, please; you can merge the PR afterwards

2023-09-21 10:20 UTC, merged

2023-09-21 10:46 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12540