#11569 - Add duplicate detection to import
SORMAS-Foundation/SORMAS-Project pull request #12554
Opened 2023-09-21 10:57 UTC by MateStrysewske

Fixes #11569

2023-09-22 10:21 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12554

2023-09-25 08:11 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12554

2023-09-26 08:49 UTC, sergiupacurariu requested changes

2023-09-26 08:49 UTC, sergiupacurariu commented on sormas-backend/src/main/java/de/symeda/sormas/backend/environment/EnvironmentService.java
> +				cb.lessThanOrEqualTo(joins.getLocation().get(Location.LONGITUDE), criteria.getGpsLonTo() + 0.02)));
GPS latitude and longitude can take also negative values in this case the evaluation of "-0.02" and "+0.02" should work the other way around. Also, there is a situation when you are within less than 0.02 from the equator or from the prime meridian.

2023-09-26 08:49 UTC, sergiupacurariu commented on sormas-backend/src/test/java/de/symeda/sormas/backend/environment/EnvironmentServiceTest.java
> +			e.getLocation().setLatitude(20D);
the GPS Latitude values should have a range between [-90, 90]

2023-09-26 08:49 UTC, sergiupacurariu commented on sormas-backend/src/test/java/de/symeda/sormas/backend/environment/EnvironmentServiceTest.java
> +			e.getLocation().setLongitude(20D);
the GPS Longitude values should have a range between [-180, 180]

2023-09-26 08:51 UTC, sergiupacurariu commented
when an Environment that is imported has all the fields that would match a duplicate but does not have an environment name which is mandatory, the error is that there is a duplicate instead of a missing mandatory field.

2023-09-29 08:31 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12554

2023-10-02 09:23 UTC, sergiupacurariu approved these changes

2023-10-02 09:23 UTC, merged