Feature 11574 environment samples on dashboard map
SORMAS-Foundation/SORMAS-Project pull request #12581
Opened 2023-09-27 10:15 UTC by leventegal-she

Fixes #11574

2023-09-27 10:37 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12581

2023-10-03 09:12 UTC, sergiupacurariu requested changes

2023-10-03 15:20 UTC, sergiupacurariu requested changes

2023-10-03 15:20 UTC, sergiupacurariu commented on sormas-backend/src/main/java/de/symeda/sormas/backend/dashboard/sample/SampleDashboardService.java
> +	public Long countEnvironmentSamplesForMap(SampleDashboardCriteria criteria) {
same like for "getEnvironmentalSamplesForMap" method

2023-10-09 08:48 UTC, leventegal-she commented on sormas-api/src/main/java/de/symeda/sormas/api/dashboard/sample/MapSampleDto.java
> +	public MapSampleDto(Double longitude, Double latitude, Double associatedEntityLongitude, Double associatedEntityLatitude) {
it is used by the JPA query of getting the samples for the map

2023-10-09 10:09 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12581

2023-10-10 09:51 UTC, sergiupacurariu approved these changes

2023-10-10 09:52 UTC, merged