#12666 Prevent district level users in the web app from editing sendi…
SORMAS-Foundation/SORMAS-Project pull request #12689
Opened 2023-10-24 10:37 UTC by leventegal-she

…ng information of environment samples that they have not created

Fixes #12666

2023-10-24 11:05 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12689

2023-10-25 09:54 UTC, MateStrysewske requested changes
Not really directly related to this issue, but while you're already at it, maybe you can still fix it: The weather conditions field is editable even if the rest of the shipment information fields is read only. Apart from that, seems to work fine :)

2023-10-26 13:05 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12689

2023-10-30 09:09 UTC, MateStrysewske approved these changes

2023-10-30 09:10 UTC, merged