Feature 12573 automatic lab message processing
SORMAS-Foundation/SORMAS-Project pull request #12688
Opened 2023-10-23 19:16 UTC by leventegal-she

Fixes #12573

2023-10-24 08:53 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12688

2023-10-24 11:48 UTC, MateStrysewske requested changes
As far as I can see, the new saveAndProcess method is nowhere actually called, so outside of unit tests, the automatic processing isn't working at all

2023-10-24 11:59 UTC, leventegal-she commented
> As far as I can see, the new saveAndProcess method is nowhere actually called, so outside of unit tests, the automatic processing isn't working at all

As I've put in the PR description:
Will need an eSante ticket for changing the push endpoint to call the saveAndProcessLabmessage facade method
The automaticProcessingPossible seems to be useless in this case

2023-10-24 12:02 UTC, leventegal-she commented on sormas-api/src/main/java/de/symeda/sormas/api/externalmessage/ExternalMessageFacade.java
> +	ExternalMessageDto saveAndProcessLabmessage(@Valid ExternalMessageDto dto);
It processes an external message of type LAB_MESSAGE so I wouldn't add the general name you suggested but instead let's add a safety check inside the method and throw an exception if the external message type is not LAB_MESSAGE

Note that Physician reports are processed in another flow

2023-10-25 10:13 UTC, MateStrysewske commented
Sending this external message leads to an error that does not happen when I use the normal `save` method:

```
<ClinicalDocument xmlns="urn:hl7-org:v3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" classCode="DOCCLIN" moodCode="EVN">
    <realmCode code="LU"/>
    <templateId root="2.16.840.1.113883.10.20.30"/>
    <code code="DT-00003" codeSystem="1.3.182.5.9" displayName="Déclaration laboratoire de maladie infectieuse"/>
    <recordTarget>
        <patientRole>
            <id extension="123456" root="1.3.182.3.1.1.123456.2"/>
            <id extension="987654" root="1.3.182.4.4"/>
            <addr use="H">
                <streetAddressLine>Poststraße 12</streetAddressLine>
                <city>Braunschweig</city>
                <postalCode>38114</postalCode>
                <country>DE</country>
            </addr>
            <telecom use="MC" value="tel:+00000"/>
            <patient>
                <name>
                    <family qualifier="BR">Stanley</family>
                    <given>Anakin</given>
                </name>
                <administrativeGenderCode code="M" codeSystem="2.16.840.1.113883.5.1" codeSystemName="HL7:AdministrativeGender" displayName="Masculin"/>
                <birthTime value="19000101"/>
            </patient>
        </patientRole>
    </recordTarget>
    <custodian> <!-- lab information -->
        <assignedCustodian>
            <representedCustodianOrganization>
                <id extension="123456789" root="1.3.182.4.1"/>
                <name>Laboratory</name>
                <addr use="WP">
                    <postalCode>1234</postalCode>
                    <city>Luxembourg</city>
                </addr>
            </representedCustodianOrganization>
        </assignedCustodian>
    </custodian>
    <participant typeCode="REF">
        <templateId root="1.3.6.1.4.1.19376.1.3.3.1.6"/>
        <associatedEntity classCode="PROV">
            <id extension="90719450" root="1.3.182.4.6"/>
            <addr use="WP">
                <streetAddressLine>Prescriber Street 23</streetAddressLine>
                <postalCode>2120</postalCode>
                <city>Luxembourg</city>
                <country>LUX</country>
            </addr>
            <telecom use="WP" value="tel:+11111"/>
            <associatedPerson>
                <name>
                    <family>Criber</family>
                    <given>Pres</given>
                </name>
            </associatedPerson>
        </associatedEntity>
    </participant>
    <documentationOf>
        <serviceEvent>
            <effectiveTime value="20201012054621+0200"/>
        </serviceEvent>
    </documentationOf>
    <componentOf>
        <encompassingEncounter>
            <effectiveTime value="20201012054621+0200"/>
        </encompassingEncounter>
    </componentOf>
    <component>
        <structuredBody>
            <component>
                <section>
                    <code code="SARS" codeSystem="1.3.182.5.20" />
                    <entry>
                        <organizer classCode="CLUSTER" moodCode="EVN">
                            <component>
                                <observation classCode="OBS" moodCode="EVN">
                                    <code code="SARS-1" codeSystem="1.3.182.5.21"/>
                                    <value value="CONF"/>
                                </observation>
                            </component>
                            <component>
                                <observation classCode="OBS" moodCode="EVN">
                                    <code code="SARS-100" codeSystem="1.3.182.5.21"/>
                                    <value value="36" xsi:type="REAL"/>
                                </observation>
                            </component>
                            <component>
                                <observation classCode="OBS" moodCode="EVN">
                                    <code code="SARS-101" codeSystem="1.3.182.5.21"/>
                                    <value value="37" xsi:type="REAL"/>
                                </observation>
                            </component>
                            <component>
                                <observation classCode="OBS" moodCode="EVN">
                                    <code code="SARS-102" codeSystem="1.3.182.5.21"/>
                                    <value value="38" xsi:type="REAL"/>
                                </observation>
                            </component>
                            <component>
                                <observation classCode="OBS" moodCode="EVN">
                                    <code code="SARS-103" codeSystem="1.3.182.5.21"/>
                                    <value value="39" xsi:type="REAL"/>
                                </observation>
                            </component>
                            <component>
                                <observation classCode="OBS" moodCode="EVN">
                                    <code code="SARS-104" codeSystem="1.3.182.5.21"/>
                                    <value value="40" xsi:type="REAL"/>
                                </observation>
                            </component>
                            <component>
                                <observation classCode="OBS" moodCode="EVN">
                                    <code code="SARS-105" codeSystem="1.3.182.5.21"/>
                                    <value value="41" xsi:type="REAL"/>
                                </observation>
                            </component>
                            <component>
                                <observation classCode="OBS" moodCode="EVN">
                                    <code code="SARS-106" codeSystem="1.3.182.5.21"/>
                                    <value value="42" xsi:type="REAL"/>
                                </observation>
                            </component>
                        </organizer>
                    </entry>
                </section>
            </component>
        </structuredBody>
    </component>
</ClinicalDocument>
```

Stack trace: 

```
javax.ejb.TransactionRolledbackLocalException: Client's transaction aborted
	at com.sun.ejb.containers.EJBContainerTransactionManager.useClientTx(EJBContainerTransactionManager.java:345)
	at com.sun.ejb.containers.EJBContainerTransactionManager.preInvokeTx(EJBContainerTransactionManager.java:238)
	at com.sun.ejb.containers.BaseContainer.preInvokeTx(BaseContainer.java:4563)
	at com.sun.ejb.containers.BaseContainer.preInvoke(BaseContainer.java:2039)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:210)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:90)
	at com.sun.proxy.$Proxy573.getByUuid(Unknown Source)
	at de.symeda.sormas.backend.externalmessage.__EJB31_Generated__ExternalMessageService__Intf____Bean__.getByUuid(Unknown Source)
	at de.symeda.sormas.backend.externalmessage.ExternalMessageFacadeEjb.save(ExternalMessageFacadeEjb.java:264)
	at de.symeda.sormas.backend.externalmessage.ExternalMessageFacadeEjb.save(ExternalMessageFacadeEjb.java:227)
	at de.symeda.sormas.backend.externalmessage.ExternalMessageFacadeEjb.saveAndProcessLabmessage(ExternalMessageFacadeEjb.java:246)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:588)
	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:408)
	at com.sun.ejb.containers.BaseContainer.invok [...]

2023-10-26 12:46 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12688

2023-10-27 08:43 UTC, MateStrysewske requested changes
Lab messages aren't automatically processed for me at all; I've set up my system to use the Luxembourg locale and have submitted an external message with a unique person that should be automatically processable, but that doesn't happen and I still have to do it manually. Anything else I'm missing to make this work outside of unit tests? I'm of course calling the saveAndProcessLabmessage method in the ReST endpoint.

2023-10-31 08:36 UTC, leventegal-she commented
> Lab messages aren't automatically processed for me at all; I've set up my system to use the Luxembourg locale and have submitted an external message with a unique person that should be automatically processable, but that doesn't happen and I still have to do it manually. Anything else I'm missing to make this work outside of unit tests? I'm of course calling the saveAndProcessLabmessage method in the ReST endpoint.

Can you please post the labmessage you're pushing to the adapter?

2023-11-03 11:53 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12688

2023-11-03 12:49 UTC, MateStrysewske approved these changes

2023-11-03 12:49 UTC, merged