Feature 11435 assign multiple limited diseases to users
SORMAS-Foundation/SORMAS-Project pull request #12723
Opened 2023-10-31 15:25 UTC by leventegal-she

Fixes #11435

2023-10-31 18:19 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12723

2023-11-01 12:21 UTC, MateStrysewske requested changes

2023-11-03 13:57 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12723

2023-11-06 09:24 UTC, MateStrysewske approved these changes
Let's wait for the release before merging this PR

2023-11-10 10:33 UTC, merged