#4837 - Only show cases in the users jurisdiction by default
SORMAS-Foundation/SORMAS-Project pull request #12720
Opened 2023-10-30 18:50 UTC by carina29

Fixes #4837

2023-10-30 19:13 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12720

2023-11-01 14:31 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12720

2023-11-03 13:41 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12720

2023-11-03 13:53 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12720

2023-11-03 14:12 UTC, MateStrysewske requested changes
The code contains logic that is not necessary in the mobile app. There's no need for ANY additionally executed code when `includeCasesFromOtherJurisdictions` or `includeContactsFromOtherJurisdictions` is true because, by default, the lists show all the entities in the database anyway.

The only thing that's necessary is that, if the new filter is false, IN ADDITION to the existing code, add predicates that make sure that only data from the same jurisdiction as the users' is shown (i.e. the jurisdiction switch part).

That means:
- Remove the new code that checks the reporting user, responsible user, etc.
- ONLY call the whole jurisdiction check logic when the new filter is set to false

2023-11-03 14:12 UTC, MateStrysewske commented on sormas-app/app/src/main/java/de/symeda/sormas/app/backend/caze/CaseDao.java
> +			case REGION:
Nation and region level are not necessary; users with these jurisdiction levels don't have access to the mobile app

2023-11-03 14:12 UTC, MateStrysewske commented on sormas-app/app/src/main/java/de/symeda/sormas/app/backend/contact/ContactDao.java
> +			case REGION:
Same here

2023-11-03 14:12 UTC, MateStrysewske commented on sormas-app/app/src/main/java/de/symeda/sormas/app/backend/contact/ContactDao.java
> +		case REGION:
Region is unnecessary here as well

2023-11-03 14:12 UTC, MateStrysewske commented on sormas-app/app/src/main/java/de/symeda/sormas/app/backend/contact/ContactDao.java
> +	public Where<Contact, Long> createJurisdictionFilterWithoutCase(Where<Contact, Long> where, ContactCriteria contactCriteria) throws SQLException {
Call this `createJurisdictionFilter` and the other method `createJurisdictionFilterForCase`

2023-11-03 14:48 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12720

2023-11-03 15:13 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12720

2023-11-03 15:13 UTC, carina29 commented
> The code contains logic that is not necessary in the mobile app. There's no need for ANY additionally executed code when `includeCasesFromOtherJurisdictions` or `includeContactsFromOtherJurisdictions` is true because, by default, the lists show all the entities in the database anyway.
> 
> The only thing that's necessary is that, if the new filter is false, IN ADDITION to the existing code, add predicates that make sure that only data from the same jurisdiction as the users' is shown (i.e. the jurisdiction switch part).
> 
> That means:
> 
> * Remove the new code that checks the reporting user, responsible user, etc.
> * ONLY call the whole jurisdiction check logic when the new filter is set to false

I've removed the parts you've mentioned.

2023-11-03 15:40 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12720

2023-11-06 09:36 UTC, MateStrysewske requested changes
I'll do some testing after the release :)

2023-11-06 09:36 UTC, MateStrysewske commented on sormas-app/app/src/main/java/de/symeda/sormas/app/backend/caze/CaseDao.java
> +		//whoever created the case or is assigned to it is allowed to access it
Unnecessary comment

2023-11-06 20:35 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12720

2023-11-13 08:31 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12720

2023-11-13 08:46 UTC, MateStrysewske requested changes
Please change the text colour of the filter; should be the same colour as e.g. the text input of the free text filter (not the placeholder); also don't make it bold (I believe it is right now). Logic seems to work fine :)

2023-11-13 09:58 UTC, carina29 commented
> Please change the text colour of the filter; should be the same colour as e.g. the text input of the free text filter (not the placeholder); also don't make it bold (I believe it is right now). Logic seems to work fine :)

I've changed the font and colour as you've suggested ( is the same styling as we have for the filter text):
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/860fdf6b-6fa8-40af-85d2-60105c45f583)

2023-11-13 10:25 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12720

2023-11-14 08:40 UTC, MateStrysewske approved these changes

2023-11-14 08:41 UTC, merged