#12461 View existing and create new email templates in the configurat…
SORMAS-Foundation/SORMAS-Project pull request #12762
Opened 2023-11-16 07:13 UTC by leventegal-she

…ion screen

Fixes #12461

@MateStrysewske Plase add the user guide. The file name used in the code is `SORMAS_Email_Template_Guide.pdf`

2023-11-16 07:31 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12762

2023-11-16 13:57 UTC, MateStrysewske requested changes
Looks good apart from this minor thing; I'll take care of the guide tomorrow

2023-11-16 13:57 UTC, MateStrysewske commented on sormas-api/src/main/java/de/symeda/sormas/api/feature/FeatureType.java
> +	EXTERNAL_EMAILS(true, false, null, null, null);
Please put this into the correct section (see issue description)

2023-11-17 07:58 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12762

2023-11-17 08:14 UTC, MateStrysewske approved these changes

2023-11-17 08:14 UTC, merged