#12841 Add validation to the national health ID field
SORMAS-Foundation/SORMAS-Project pull request #12897
Opened 2024-01-18 09:29 UTC by leventegal-she

Fixes #12841

2024-01-18 09:47 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12897

2024-01-25 08:33 UTC, MateStrysewske requested changes
National health ID does not seem properly validated against the birth date if it exists; if no birth date is entered, validation seems correct

2024-01-25 11:22 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12897

2024-01-25 11:22 UTC, MateStrysewske approved these changes

2024-01-25 11:39 UTC, merged