#12809 - Add support for HIDE_JURISDICTION feature to campaigns
SORMAS-Foundation/SORMAS-Project pull request #12896
Opened 2024-01-17 12:57 UTC by carina29

Fixes #12809

2024-01-17 13:15 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12896

2024-01-18 12:51 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12896

2024-01-18 12:52 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12896

2024-01-18 12:55 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12896

2024-01-22 14:43 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12896

2024-01-22 14:48 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12896

2024-01-23 08:41 UTC, MateStrysewske requested changes

2024-01-23 08:41 UTC, MateStrysewske commented on sormas-ui/src/main/java/de/symeda/sormas/ui/campaign/campaigndata/CampaignDataGrid.java
> +		if (FacadeProvider.getFeatureConfigurationFacade().isFeatureEnabled(FeatureType.HIDE_JURISDICTION_FIELDS)) {
Replace with UiUtil.enabled

2024-01-23 08:41 UTC, MateStrysewske commented on sormas-ui/src/main/java/de/symeda/sormas/ui/campaign/campaigndata/CampaignFormDataEditForm.java
> +			cbArea.setValue(FacadeProvider.getRegionFacade().getByUuid(defaultRegion.getUuid()).getArea());
Will throw a NPE if there is no default region; there will be an error when trying to submit the form anyway in this case, but I'd rather not have an exception thrown here already

2024-01-23 08:41 UTC, MateStrysewske commented on sormas-ui/src/main/java/de/symeda/sormas/ui/campaign/campaignstatistics/CampaignStatisticsGrid.java
> +			!FacadeProvider.getFeatureConfigurationFacade().isFeatureEnabled(FeatureType.HIDE_JURISDICTION_FIELDS)
Use UiUtil.disabled

2024-01-23 08:41 UTC, MateStrysewske commented on sormas-ui/src/main/java/de/symeda/sormas/ui/campaign/campaignstatistics/CampaignStatisticsView.java
> +		if (FacadeProvider.getFeatureConfigurationFacade().isFeatureEnabled(FeatureType.HIDE_JURISDICTION_FIELDS)) {
Use UiUtil.enabled

2024-01-23 09:37 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12896

2024-01-23 10:35 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12896

2024-01-23 12:50 UTC, MateStrysewske approved these changes

2024-01-23 12:50 UTC, merged