#12852 - Show layers based on user rights
SORMAS-Foundation/SORMAS-Project pull request #12942
Opened 2024-02-06 11:42 UTC by MateStrysewske

Fixes #12852

2024-02-06 12:00 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12942

2024-02-06 13:35 UTC, carina29 commented
@MateStrysewske  I've also tested the feature branch. 

If the user does not have any view rights from the Layers section, an empty dropdown will appear (in this scenario I've had only the Samples related rights and the Access to the Samples dashboard but probably can be reproduced with other combinations too when we have access only to one dashboard without view rights for other entities):
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/5d079b30-211f-484b-90ba-2e284b81ae90)

![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/8c58cc19-f840-4873-9b5c-b24de1b4f5bc)

User Rights for my test user:
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/e77c7245-ef4a-4ab0-b865-d32bb36fce67)
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/7c7acde7-4139-4b08-8d21-bf75fbeedf2a)
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/1b230396-be54-40c0-a8c2-156be335743f)
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/a55c9aae-2d39-41d1-8a8b-3df4d25b54d8)
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/cc057e3d-93a0-4eb1-ac92-2e6b518907c9)

![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/2c7473d1-5036-4170-9967-0315474269c7)

![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/704b0604-edb6-48b0-8947-f245f7e0b74e)


I'm not sure how should we proceed in this case : Disable the button, hide the button or maybe you have other ideas?

2024-02-06 13:50 UTC, carina29 requested changes

2024-02-06 13:50 UTC, carina29 commented on sormas-ui/src/main/java/de/symeda/sormas/ui/dashboard/map/DashboardMapComponent.java
I've added a comment to this PR.

2024-02-07 10:27 UTC, carina29 approved these changes

2024-02-07 10:41 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12942

2024-02-07 10:48 UTC, merged