#4659 - Use the methods from UiUtil.java
SORMAS-Foundation/SORMAS-Project pull request #13026
Opened 2024-03-04 14:23 UTC by carina29

Fixes #4659

2024-03-04 14:43 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13026

2024-03-05 09:47 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13026

2024-03-05 11:40 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13026

2024-03-05 13:25 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13026

2024-03-05 13:52 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13026

2024-03-05 14:51 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13026

2024-03-06 14:29 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13026

2024-03-06 15:06 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13026

2024-03-06 15:11 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13026

2024-03-06 15:25 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13026

2024-03-06 15:46 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13026

2024-03-06 18:10 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13026

2024-03-12 13:27 UTC, leventegal-she requested changes

2024-03-12 13:27 UTC, leventegal-she commented on sormas-ui/src/main/java/de/symeda/sormas/ui/UiUtil.java
> +	public static String getUuid() {
please rename to `getUserUuid` to be clear what uuid it returns

2024-03-12 14:47 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13026

2024-03-12 15:01 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13026

2024-03-13 07:53 UTC, leventegal-she approved these changes

2024-03-13 07:53 UTC, merged