#13034 -Add TASK_VIEW_ARCHIVED user rights and the necessary changes
SORMAS-Foundation/SORMAS-Project pull request #13049
Opened 2024-03-19 15:24 UTC by carina29

Fixes #13034

2024-03-19 15:42 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13049

2024-03-20 12:08 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13049

2024-03-20 12:15 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13049

2024-03-20 12:49 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13049

2024-03-20 14:25 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13049

2024-03-22 13:58 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13049

2024-04-18 07:56 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13049

2024-05-07 09:18 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13049

2024-05-07 12:30 UTC, leventegal-she requested changes

2024-05-07 12:30 UTC, leventegal-she commented on sormas-api/src/main/resources/enum.properties
> +UserRight.Desc.TASK_VIEW_ARCHIVED = View archived tasks
should be `Able to view ...`

2024-05-07 12:30 UTC, leventegal-she commented on sormas-backend/src/main/java/de/symeda/sormas/backend/campaign/CampaignFacadeEjb.java
> +	@RightsAllowed({
@RightsAllowed allows access if the user has one of the given rights so a user with view archived right will be allowed to dearchive a campaign

The view archive right must be checked in the method

Please change this for all the dearchive methods

2024-05-08 11:42 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13049

2024-05-08 13:25 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13049

2024-05-08 15:57 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13049

2024-05-08 16:42 UTC, carina29 commented on sormas-ui/src/main/java/de/symeda/sormas/ui/campaign/CampaignController.java
> +		if (FacadeProvider.getCampaignFacade().isArchived(campaignDto.getUuid()) && !UiUtil.permitted(UserRight.CAMPAIGN_VIEW_ARCHIVED)) {
I've found a problem related to the exception throwing (can be reproduced for all the entities): 
In single archive mode when the logged-in user does not have VIEW_ARCHIVED_X right the above exception will be shown before the Confirmation pop-up disappears.

![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/7b32eb7c-22d5-4e81-9945-d23e6e19c538)

I'm not sure what should happen in this scenario: navigation to the entity directory, finding a solution to display the exception later or something else.

2024-05-13 05:51 UTC, leventegal-she requested changes

2024-05-13 05:51 UTC, leventegal-she commented on sormas-ui/src/main/java/de/symeda/sormas/ui/campaign/CampaignController.java
> +		if (FacadeProvider.getCampaignFacade().isArchived(campaignDto.getUuid()) && !UiUtil.permitted(UserRight.CAMPAIGN_VIEW_ARCHIVED)) {
this check should be don on the backend to avoid viewing archived entities through the rest api

Please change it for all the entities

2024-05-14 08:10 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13049

2024-05-14 14:06 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13049

2024-05-15 07:20 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13049

2024-05-16 10:21 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13049

2024-05-16 10:30 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13049

2024-05-23 09:58 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13049

2024-05-27 07:09 UTC, leventegal-she approved these changes

2024-05-27 07:10 UTC, merged