Feature #13033 sync users from keycloak
SORMAS-Foundation/SORMAS-Project pull request #13060
Opened 2024-03-27 12:20 UTC by leventegal-she

Fixes #13033

2024-03-27 12:39 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13060

2024-03-28 17:02 UTC, sergiupacurariu requested changes

2024-03-28 17:02 UTC, sergiupacurariu commented on sormas-backend/src/main/java/de/symeda/sormas/backend/common/CronService.java
> +		if (userFacade.isSyncEnabled() && featureConfigurationFacade.isFeatureEnabled(FeatureType.AUTH_PROVIDER_TO_SORMAS_USER_SYNC)) {
these two elements can never be both true so the code within if clause will never run

2024-03-28 17:15 UTC, sergiupacurariu commented
sync does not work since there is no default role for new users from authentication provider (Keycloak in this case)

2024-04-11 14:44 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13060

2024-04-11 14:51 UTC, merged