Feature 13067 case reference number on case and contact
SORMAS-Foundation/SORMAS-Project pull request #13088
Opened 2024-04-25 11:42 UTC by leventegal-she

Fixes #13067

2024-04-25 13:10 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13088

2024-04-26 13:38 UTC, carina29 requested changes

2024-04-26 13:38 UTC, carina29 commented on sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseExportDto.java
> +		return caseReferenceNumber;
I think that caseReference should not be displayed in the export files (based on the acceptance criteria "Case Reference is only shown when self reporting feature is enabled") when FeatureType.SELF_REPORTING is disabled.

Currently, when  FeatureType.SELF_REPORTING is disabled, the column will not appear in the grid as it was requested ( Contacts and Cases) but will appear in the Detailed exports for Cases for Contacts.

![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/6f5d9ec4-c01a-4233-80b7-b53c1fad6fb9)
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/f5db46d1-3004-4d92-9f33-ac44938739ce)

![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/6fcd368b-eb99-4f8c-92e2-0a49e124edf4)

2024-05-08 16:19 UTC, carina29 commented
There is a failing test: ArchitectureTest.dontUseFacadeProviderRule

2024-05-10 07:16 UTC, carina29 requested changes
Failing test

2024-05-13 07:20 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13088

2024-05-13 09:32 UTC, carina29 approved these changes

2024-05-13 10:03 UTC, merged