#13070 - Add export (basic and detailed) and import
SORMAS-Foundation/SORMAS-Project pull request #13103
Opened 2024-05-22 17:56 UTC by carina29

Fixes #13070

2024-05-24 11:22 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13103

2024-06-04 07:32 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13103

2024-06-04 11:58 UTC, leventegal-she requested changes

2024-06-04 11:58 UTC, leventegal-she commented on sormas-backend/src/main/java/de/symeda/sormas/backend/importexport/ImportFacadeEjb.java
> +			SelfReportDto.class.getDeclaredField("investigationStatus"),
reflection is slow so here please use strings only, and use constants from the dto class

2024-06-04 11:58 UTC, leventegal-she commented on sormas-backend/src/main/java/de/symeda/sormas/backend/importexport/ImportFacadeEjb.java
> +			SelfReportDto.class.getDeclaredField("INVESTIGATION_STATUS"),
static fields are skipped in the `appendListOfFields` method

2024-06-04 11:58 UTC, leventegal-she commented on sormas-backend/src/main/java/de/symeda/sormas/backend/selfreport/SelfReportImportFacadeEjb.java
> +		if (values[0].isBlank() || !EnumUtils.isValidEnum(SelfReportType.class, values[0])) {
having the type in the first column is not a must, there is no need to check it just do a build with null all the time

2024-06-04 13:48 UTC, leventegal-she requested changes

2024-06-04 13:57 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13103

2024-06-04 14:04 UTC, leventegal-she approved these changes

2024-06-04 14:23 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13103

2024-06-04 14:29 UTC, merged