Feature 13085 self report edit
SORMAS-Foundation/SORMAS-Project pull request #13100
Opened 2024-05-14 08:32 UTC by leventegal-she

Fixes #13085

2024-05-14 09:10 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13100

2024-05-17 08:52 UTC, carina29 requested changes
There are some conflicts in strings.properties
and SelfReportGrid.java

2024-05-17 08:52 UTC, carina29 commented on sormas-backend/src/main/resources/sql/sormas_schema.sql
> +SELECT id, 'SELF_REPORT_ARCIVE'
Typo in user right

2024-05-22 09:07 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13100

2024-05-23 09:23 UTC, merged

2024-05-23 09:23 UTC, carina29 reviewed
Approved PR.