#13140 Restore User Synchronization Button and Ensure Proper Keycloak…
SORMAS-Foundation/SORMAS-Project pull request #13146
Opened 2024-09-04 12:52 UTC by leventegal-she

… Synchronization Configuration

Fixes #13140

2024-09-04 13:13 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13146

2024-09-09 13:11 UTC, sergiupacurariu requested changes

2024-09-09 13:11 UTC, sergiupacurariu commented on sormas-api/src/main/resources/strings.properties
> +messageSyncUsersFromAuthProviderConfigurationError=Syncing users from authentication provider is not possible because the configuration is incorrect. Please contact an admin and inform them about thi
shouldn't have a more specific message since to this feature have access only "admin" users?

2024-09-09 13:14 UTC, sergiupacurariu commented
I would add description for "AUTH_PROVIDER_TO_SORMAS_USER_SYNC" feature configuration to the wiki page that contains feature configuration options: 
https://github.com/SORMAS-Foundation/SORMAS-Project/wiki/Feature-Configuration-Options

2024-09-09 13:52 UTC, sergiupacurariu approved these changes

2024-09-09 13:53 UTC, merged