Feature 13093 data protection update
SORMAS-Foundation/SORMAS-Project pull request #13170
Opened 2024-10-23 13:22 UTC by sergiupacurariu

Fixes #13093

2024-10-23 13:42 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13170

2024-10-25 11:50 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13170

2024-10-25 18:43 UTC, leventegal-she requested changes

2024-10-25 18:43 UTC, leventegal-she commented on sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseDataDto.java
> +	@SensitiveData
Shouldn't this and the other fields be sensitive only for luxembourg servers?

2024-10-25 18:43 UTC, leventegal-she commented on sormas-backend/src/main/java/de/symeda/sormas/backend/info/EntityColumn.java
> +		} else {
please change to else if

2024-10-25 18:43 UTC, leventegal-she commented on sormas-backend/src/main/java/de/symeda/sormas/backend/info/EntityColumn.java
> +		String prefixDescription = I18nProperties.getPrefixDescription(fieldData.getI18NPrefix(), fieldData.getField().getName(), "");
please rename to fieldDescription

2024-10-25 18:43 UTC, leventegal-she commented on sormas-ui/src/main/java/de/symeda/sormas/ui/utils/RichTextAreaCustom.java
> +public class RichTextAreaCustom extends RichTextArea {
is this still needed?

2024-10-25 18:43 UTC, leventegal-she commented on sormas-ui/src/main/java/de/symeda/sormas/ui/clinicalcourse/HealthConditionsForm.java
> +		if (UiUtil.permitted(UserRight.SEE_SENSITIVE_DATA_IN_JURISDICTION)) {
making this field inaccessible should be done similarly like you did  for the NullableOptionGroup field

2024-10-25 18:43 UTC, leventegal-she commented on sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseDataDto.java
> +	@SensitiveData
I remember we discussed on the planning that if we make the health conditions on the case sensitive, then it has to be sensitive on all other places it is used

2024-10-25 18:43 UTC, leventegal-she commented on sormas-backend/src/main/java/de/symeda/sormas/backend/info/EntityColumn.java
> +		String prefixDescription = I18nProperties.getPrefixDescription(fieldData.getI18NPrefix(), fieldData.getField().getName(), "");
The data protection dictionary is country disease and feature dependent so it should not have this extra description, but should not show personal or sensitive in the data protection colum

2024-10-28 07:30 UTC, sergiupacurariu commented on sormas-api/src/main/java/de/symeda/sormas/api/caze/CaseDataDto.java
> +	@SensitiveData
updated in VaccinationDto, CaseExportDto and ContactDto

2024-10-28 07:32 UTC, sergiupacurariu commented on sormas-backend/src/main/java/de/symeda/sormas/backend/info/EntityColumn.java
> +		} else {
changed

2024-10-28 07:36 UTC, sergiupacurariu commented on sormas-ui/src/main/java/de/symeda/sormas/ui/utils/RichTextAreaCustom.java
> +public class RichTextAreaCustom extends RichTextArea {
no, it's not needed anymore. Removed.

2024-10-29 13:11 UTC, leventegal-she requested changes

2024-10-29 13:11 UTC, leventegal-she commented on sormas-ui/src/main/java/de/symeda/sormas/ui/AboutView.java
> +			try {
please revert this

2024-10-29 13:11 UTC, leventegal-she commented on sormas-ui/src/main/java/de/symeda/sormas/ui/clinicalcourse/HealthConditionsForm.java
> +	private boolean displayFieldsAllowed() {
please use similar solution like you did for the NullableOptionGroup

2024-10-30 08:56 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13170

2024-10-30 09:19 UTC, leventegal-she approved these changes

2024-10-30 09:19 UTC, merged