Birthdate month does not show "Empty" instead of "confidential" when …
SORMAS-Foundation/SORMAS-Project pull request #13180
Opened 2024-11-06 07:52 UTC by sergiupacurariu

…restrictions apply #13179

Fixes #13179

2024-11-06 08:27 UTC, leventegal-she requested changes

2024-11-06 08:27 UTC, leventegal-she commented on sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonEditForm.java
> +//		birthDateMonth.addItems(DateHelper.getMonthsInYear());
Please delete the commented code

2024-11-07 09:17 UTC, sergiupacurariu commented on sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonEditForm.java
> +//		birthDateMonth.addItems(DateHelper.getMonthsInYear());
removed the commented code

2024-11-07 09:35 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13180

2024-11-11 13:02 UTC, merged