#13183 Add New Influenza Disease Types and Modify Display for SORMAS-…
SORMAS-Foundation/SORMAS-Project pull request #13188
Opened 2024-11-19 07:53 UTC by leventegal-she

…Luxembourg

Fixes #13183

2024-11-19 08:18 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13188

2024-12-05 14:13 UTC, sergiupacurariu requested changes

2024-12-05 14:13 UTC, sergiupacurariu commented on sormas-api/src/main/java/de/symeda/sormas/api/Disease.java
> +	INFLUENZA(true, true, true, true, false, 0, true, false, false),
the previous "Influenza_A" and "Influenza_B" were not enabled for aggregate report. The new "Influenza" should be the same.

2024-12-06 10:50 UTC, sormas-vitagroup commented
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13188

2024-12-06 12:58 UTC, sergiupacurariu approved these changes

2024-12-06 12:58 UTC, merged